### ISSUE TITLE
Redirects might not be working /requests > /manual-visits

### ISSUE THREAD

**Issue by dulldave** [inertiajs/inertiajs.com#107]
I'm not sure how much of an issue this is but I noticed that the recent change [here](https://github.com/inertiajs/inertiajs.com/commit/d177f635949079828eab2e8a46de70bac409a304#diff-5d0c276360a637d1b787a57760665fbeR5-R13) which replaces the "requests" page with the "manual visits" page introduced a redirect from the old path to the new one.

However, requesting the old path now looks to be returning a 404 instead of a redirect and I'm guessing that isn't intended behaviour.

Just thought I'd give you a bit of a heads up for any future changes (that is if this is an issue).

**Comment by reinink** [comment]
Hmm, shoot, I did create a Next.js redirect for this, but evidently that doesn't work on Netlify. 🤔 

https://github.com/inertiajs/inertiajs.com/blob/ccca0bc64661818c87719077565c08469e78cbf5/next.config.js#L5-L13

**Comment by reinink** [comment]
Figured it out. Needed to use a Netlify [redirect](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file).

The page https://inertiajs.com/requests now successfully redirects to https://inertiajs.com/manual-visits. 👍 

Thanks for reporting!
