### ISSUE TITLE
Importing scripts into the header

### ISSUE THREAD

**Issue by chrisgrim** [inertiajs/inertiajs.com#159]
Hi,
I love Inertia! Its so nice to remove the blade files from the mix. I am having one issue that I am sure is an easy fix. I am trying to use stripe which requires <script src="https://js.stripe.com/v3/"></script> to be added to the header. I am having trouble figuring out how to add that with Inertia. I added VueMeta and added it here
```
<script>
    import AppLayout from '@/Layouts/AppLayout'
    export default {
        metaInfo: {
            script: [ { src: 'https://js.stripe.com/v3/' }],
        },
```
but that didn't seem to add it where I could see in the source file. Is there a way to do this?

**Comment by reinink** [comment]
I'd recommend just adding this to your `app.blade.php`, in the `<head>`. 👍 

Glad to hear you like Inertia!
