### ISSUE TITLE
Discord invitation link expired

### ISSUE THREAD

**Issue by prodigy7** [inertiajs/inertiajs.com#162]
The discord invitation link on the internet site is expired. When I try to join the discord server, i only get a message that the invite is invalid.

**Comment by reinink** [comment]
Are you certain? I just tried it, and it appears to be working still (see screenshot below). Are you able to get to this point, or does the issue happen after you enter a username?

![image](https://user-images.githubusercontent.com/882133/108429804-713f1400-720e-11eb-8182-0b6a4b504eee.png)

I am also able to access this when logged in to Discord already:

![image](https://user-images.githubusercontent.com/882133/108429961-a6e3fd00-720e-11eb-9489-a7a940709ee0.png)

Finally, I see that lots of folks have joined in the last couple days, suggesting it is still working. 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/882133/108430038-c11ddb00-720e-11eb-944a-9248a29db4cc.png)

Closing this for now. Please report back if it's still busted for you.
