### ISSUE TITLE
Client-side setup samples for vue3 incomplete

### ISSUE THREAD

**Issue by prodigy7** [inertiajs/inertiajs.com#163]
The documentation for install dependencies is incomplete. Currently there is only described, how to install vue2 dependencies. The lines

```
npm install @inertiajs/inertia @inertiajs/inertia-vue3
yarn add @inertiajs/inertia @inertiajs/inertia-vue3
```

are missing / not mentioned

**Comment by reinink** [comment]
Good catch, this has been added: a9d8ce45be37247aa24e381ce0f05176dd0cffa4
