### ISSUE TITLE
"An unexpected error has occurred."

### ISSUE THREAD

**Issue by jethromay** [inertiajs/inertiajs.com#17]
Reported on Twitter but i just thought i'd report the following issue here too, in case it gets lost. 

This happening on both Firefox & Chrome when i try view the website. This is happening on multiple devices for me, i have tried clearing cache and that doesn't seem to be the issue.

![image](https://user-images.githubusercontent.com/6702147/66458337-cd1e5800-ea72-11e9-94de-762575df4706.png)

**Comment by reinink** [comment]
Are you using any browser plugins to block JS?

**Comment by jethromay** [comment]
@reinink i thought that too, i know Lastpass has caused issues previously. I went to go and disable them now but it seems to have resolved itself, weird. Will close.
