### ISSUE TITLE
Add documentation for preserveScroll and preserveState "errors" option

### ISSUE THREAD

**Issue by emargareten** [inertiajs/inertiajs.com#199]

**Comment by LucaRed** [comment]
More details for anybody who wants to work on this issue.

Both `preserveScroll` and `preserveState` accept the [`PreserveStateOption` type](https://github.com/inertiajs/inertia/blob/71792799b852a5e6cb882d74f4abd117b15c989e/packages/core/src/types.ts#L58), which can be a boolean, an "`errors`" string or an anonymous function.

More details in the PR that introduced this feature: inertiajs/inertia#628

**Comment by driesvints** [comment]
Thanks. We'd very much appreciate a PR to the docs!

**Comment by LucaRed** [comment]
I can prepare a PR when I have time, but why closing this issue?
