### ISSUE TITLE
Update docs removing mix and adding vite

### ISSUE THREAD

**Issue by MCKevmeister** [inertiajs/inertiajs.com#245]
Currently, the docs still contain setup of both the client side and server side with Laravel mix. As Laravel has changed to support vite, a change in the docs to reflect this would be necessary.

**Comment by veerman72** [comment]
example Default Layout (vite/vue3/script setup):

`import DefaultLayoutFile from './Layouts/DefaultLayoutFile.vue'`

`resolve: (name) => {
    const page = resolvePageComponent(`
      `./Pages/${name}.vue`,
      `import.meta.glob("./Pages/**/*.vue")
    );
    page.then((module) => {
      module.default.layout = module.default.layout || DefaultLayoutFile;
    });
    return page;
  },`
