### ISSUE TITLE
Site SSL certificate

### ISSUE THREAD

**Issue by cedricfortuin** [inertiajs/inertiajs.com#260]
### What is wrong?
The SSL certificate of the site is not valid anymore.

**Comment by Snicser** [comment]
Hi,

For me it is completely working.

https://gyazo.com/43f64fd7503d6dc69f7dc2991d175cfe

**Comment by cedricfortuin** [comment]
Hi there, I tested it with several (major) browsers:

Brave: 
![image](https://user-images.githubusercontent.com/55191740/213864457-4eb6b89a-2121-42db-be89-3f07ece1bbb6.png)

Edge:
![image](https://user-images.githubusercontent.com/55191740/213864472-a3e20ea3-a1b1-4a88-84e9-ce5d8c5adb06.png)

Chrome:
![image](https://user-images.githubusercontent.com/55191740/213864492-d3483377-e323-4847-9f8a-b3ce633fe8ae.png)
(not secure)

I also cleared the cache on every browser.
What browser did you use?

**Comment by reinink** [comment]
Hey! So an SSL cert was installed on this site, we just weren't redirecting from HTTP to HTTPS automatically This has been fixed 👍

If you visit http://inertiajs.com you'll now be redirected to https://inertiajs.com.

Thanks for the heads up!
