### ISSUE TITLE
update to "code-splitting.jsx" breaks the app

### ISSUE THREAD

**Issue by JMarschner** [inertiajs/inertiajs.com#278]
My Vue3 app breaks after I update to lazy-load my pages. I think there is some writing issue in the documentation.
Someone should update the documentation at file "code-splitting.jsx" from `return pages[`./Pages/${name}.vue`] ` to `return pages[`./Pages/${name}.vue`]() `

**Comment by reinink** [comment]
Hey! Are you using the `{ eager: true }` flag? See here:

https://inertiajs.com/server-side-rendering#add-server-entry-point

**Comment by JMarschner** [comment]
Of course not because i want to split the code in several parts.
Please take a look to:
[https://inertiajs.com/code-splitting](https://inertiajs.com/code-splitting) 

This ist not a issue at code but in the documentation.

**Comment by reinink** [comment]
Ah, my misunderstanding, for some reason I thought you were talking about SSR, where you do want a single bundle.

This has been fixed: c4992ff6d731e1845161584acccb4f0e5cd2007f
