### ISSUE TITLE
Problem with router with double // in end of url

### ISSUE THREAD

**Issue by smackup** [inertiajs/inertiajs.com#326]
I accidentally discovered a problem in one of my projects, when a double slash is formed at the end of a link from a third-party resource, the router stops working properly. 

Error >"Failed to construct 'URL': Invalid URL."

You can reproduce the problem at https://inertiajs.com// for example.

I wouldn't say it's an important problem, but if it exists, it would probably be a good idea to fix it.

Great product by the way, kudos and respect.

**Comment by Verox001** [comment]
I mean, Inertia is not even throwing anything unexpected. It just tells you that the URL is invalid, which is totally correct. If you know that the URL will be malformed, you should format it before giving it anywhere.

When entering something with a double-slash in your browser, some will auto-format it for you, but some won't, so you should be formatting it even if intertia would allow URLs like that.

**Comment by driesvints** [comment]
Thanks @Verox001
