### ISSUE TITLE
ASP.NET Core community adapter was compromised

### ISSUE THREAD

**Issue by Cregennan** [inertiajs/inertiajs.com#328]
If you follow the [ASP.NET Core adapter link](https://github.com/Nothing-Works/inertia-aspnetcore) on [this](https://inertiajs.com/community-adapters) page, you will end up in renamed repository with README containing link to possibly (or probably) malicious website.</br>
<img src="https://github.com/inertiajs/inertiajs.com/assets/19265512/de888f51-f04f-4433-a65d-bc0aff8303e9" alt="drawing" width="500"/>
</br>
These changes were made 4 days ago in [this commit](https://github.com/Nothing-Works/adobe-acrobat/commit/dadfb51af9d8856382fb0219785a379a0c041a3a), I don't know if they are made intentionally by Nothing-Works or his account was cracked.

**Comment by driesvints** [comment]
Thanks. I sent in a PR.
