### ISSUE TITLE
Bug: Site visit being cancelled by ongoing reload

### ISSUE THREAD

**Issue by Verox001** [inertiajs/inertiajs.com#345]
**What's the problem?**
When the page is being reloaded, it can be indicated by the blue progress indicator at the top. While this progress indicator is indicating that a reload is occurring, clicking a link or executing `router.visit()` does not finish, when the reload finishes before the visit could be done. This means that clicking a link just reloads in a short loading with an overlay (I built myself) and then just disappears, when another reload finishes.

**How to reproduce:**
You'll need an endpoint, which takes a bit longer to finish, so you have enough time to click a link during reload. While reloading, click a link to a page, which needs some time to load as well. Make sure that the reload finishes before visit; In this case the redirect won't work and only the reload will have been finished.

**Suggestion:**
One cool way to solve this would be a priority system, where you could give each visit / reload a priority, which indicates how important a request ist. Since a redirect is more important than the reload in most cases, the redirect should cancel the reload and continue redirecting to the new page.

It would be awesome to hear some solutions from you guys as well!

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb) or [InertiaJS Discord](https://discord.gg/inertiajs) for Inertia questions
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
