### ISSUE TITLE
Sample snippets should remember framework selection

### ISSUE THREAD

**Issue by BilalBudhani** [inertiajs/inertiajs.com#46]
I have been working on integrating Inertia with Ruby on Rails application. For this, I have to spend a lot of time with documentation. A small improvement in the documentation site which could go a long way is if I select `Rails` in one of the snippets then all snippets should switch to `Rails`. 

Consider the following scenario 

<img width="741" alt="Server-side setup - Inertia js 2019-12-19 13-43-38" src="https://user-images.githubusercontent.com/1650995/71156261-a6944e80-2265-11ea-8dce-53f384f9d070.png">

I have selected `Rails` in the first snippet but I have the other snippets still shows `Laravel` code which is not relevant to me. Also, switching every snippet to `Rails` gets slightly irritating after a while. 

P.S: If we can remember the user's selection locally and pre-select their preference in every visit then it would be more awesome. 

Thanks!

**Comment by reinink** [comment]
Yup, I like this idea. It's something I considered when first building the site, but ran out of time.

**Comment by BilalBudhani** [comment]
@reinink I look into the codebase to understand if I can contribute. However, I ran into issues while trying to access `window.localStorage` in Nextjs. Can you point me in the right direction to solve this issue? I can work on this feature.
