### ISSUE TITLE
Prop children update

### ISSUE THREAD

**Issue by kufdaw** [inertiajs/inertiajs.com#62]
Hi,

whenever I have structure like this:
```
ShoppingBag: [
    name: 'sth',
    Products: [{
        price: 10,
        name: 'pizza'
    }]
]
```

and shopping bag is a prop, when I add item to products collection it doesn't get updated. However, when I change sth in main object it gets updated. How do I make data change triggered when I update nested, second level collection?

**Comment by reinink** [comment]
What was wrong? 🤣

**Comment by kufdaw** [comment]
Please delete that one, it was because in that specific request I was using axios by mistake!! Sorry for spam!!

**Comment by reinink** [comment]
All good, glad you got it figured out. 💪
